[tool.poetry]
name = "langservehub"
version = "0.1.0"
description = ""
authors = ["Erick Friis <erick@langchain.dev>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
typer = "^0.9.0"
tomli-w = "^1.0.0"
fastapi = "^0.103.2"
langserve = "^0.0.8"
uvicorn = "^0.23.2"
sse-starlette = "^1.6.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
