[tool.poetry]
name = "squawk"
version = "0.1.0"
description = ""
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
openai = "^0.28.1"
langchain = ">=0.0.313, <0.1"

[tool.langserve]
export_module = "squawk.chain"
export_attr = "chain"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
